name: Test 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Use Rust nightly
        run: rustup default nightly
      - name: Install unzip utility
        run: sudo apt-get install -y unzip
      - name: Unzip mock data
        run: unzip gravity_2k-trailer.zip
      - name: Build
        run: cargo build --verbose
      - name: Pull mock data
        run: cd hpull
      - name: Run hpull
        run:  hpull --file-path ../gravity_2k-trailer.mp4
      - name: Back
        run: cd ..
      - name: Run tests
        run: cargo test --verbose
